### PR TITLE
fix: fix some nat traversal bugs

### PR DESCRIPTION
**Pull request by YTGhost**

### CODE REVIEW

**Comment by YTGhost** [comment]
@BSWANG @njucjc @River-sh PTAL

**Comment by River-sh** [comment]
A switch should be provided in boot options to enable or disable nat traversal

**Comment by YTGhost** [comment]
> A switch should be provided in boot options to enable or disable nat traversal

ok, I'll add this switch.

**Comment by River-sh** [comment]
The fields of the Gateway API should be published here https://github.com/openyurtio/openyurt/tree/master/pkg/apis/raven/v1beta1，for instance, NATType 
func EnableCreateEdgeConnection(localEndpoint *types.Endpoint, remoteEndpoint *types.Endpoint) bool {}  pkg/networkengine/vpndriver/driver.go

**Pull request closed without merging**
